### ISSUE TITLE
Los artefactos de scrum, product backlog

### ISSUE THREAD

**Issue by NicolasRuiz81** [Guillermocba/Grupo5#10]
**Recabar información sobre product backlog, se pueden incluir imágenes y videos adicionales que aporten al tema.**

**Comment by nico153** [comment]
**¿Qué es un Product Backlog?**
El backlog de un producto es una lista de trabajo ordenado por prioridades para el equipo de desarrollo que se obtiene de la hoja de ruta y sus requisitos. Los elementos más importantes se muestran al principio del backlog del producto para que el equipo sepa qué hay que entregar primero. backlog del producto en la medida de sus capacidades, ya sea de forma continua kanban o por iteraciones scrum.
También sirve como base para planificar iteraciones. Todos los elementos de trabajo deben incluirse en el backlog: historias de usuario, bugs, cambios de diseño, deuda técnica, solicitudes de clientes, elementos de acción de la retrospectiva, etc.
![Backlog-3-1024x963](https://user-images.githubusercontent.com/108106460/177058046-d0ecd3fb-0cf1-43b4-b508-65a3e29ea31a.png)
El equipo de desarrollo no trabaja con el backlog al ritmo que dicta el propietario del producto, y este no presiona al equipo de desarrollo para que saque el trabajo adelante. En su lugar, el equipo de desarrollo saca trabajo del backlog del producto en la medida de sus capacidades, ya sea de forma continua kanban o por iteraciones scrum.

**Mantener un backlog saludable**
Una vez creado el backlog del producto, es importante mantenerlo periódicamente para que siga el ritmo del programa. Los propietarios del producto deben revisar el backlog antes de cada reunión para planificar la iteración con el objetivo de asegurar que la priorización es correcta y que se ha incorporado el feedback de la iteración anterior. La revisión periódica del backlog se denomina "backlog grooming" en entornos ágiles de habla inglesa (hay quien usa también el término "backlog refinement" o ajuste del backlog).
El backlog funciona como conexión entre el propietario del producto y el equipo de desarrollo. El propietario del producto puede cambiar la prioridad del trabajo en el backlog en cualquier momento debido a los comentarios de los clientes, los ajustes de las estimaciones y los nuevos requisitos. No obstante, una vez que el trabajo se está realizando, los cambios deben ser mínimos, ya que interrumpen el trabajo del equipo de desarrollo y afectan a la concentración, el ritmo y el ánimo.

**4 pasos para organizar tu product backlog**

**1. Product backlog item → Crea tu lista**
Apoyándote en la roadmap del producto y las exigencias de las partes interesadas, elabora una lista exhaustiva de todas las características que se esperan del producto.

Ciertas necesidades expresadas seguirán siendo ideas, mientras no cuenten con la validación para tratarlas. Las mismas pueden hacer referencia a:

el desarrollo de nuevas funciones,
la mejora de las funciones existentes,
la resolución de problemas técnicos.
Una vez se escogen las necesidades a tratar, se pueden formalizar y traducir en forma de user story.

Tu lista puede ser tan detallada como quieras, incluyendo información como:

Proyecto.
Cliente.
Departamento a cargo.
Estatus de la tarea.
Sprint que la recoge.
La anterior información puede recopilarse en:
Una hoja Excel compartida.
Un software especializado como:
[Jira](https://www.appvizer.es/organizacion-planificacion/gestion-proyectos/jira), cuyo gestor de proyectos facilita la organización y planificación de tareas.
[Kanbanize](https://www.appvizer.es/organizacion-planificacion/gestion-proyectos/kanbanize), un software de gestión de proyectos que facilita la toma de decisiones gracias a que otorga una visualización global de las tareas.
**2. Crea un mapa estratégico**
Para determinar qué características desarrollar, apóyate en una herramienta de planificación estratégica como el impact mapping. Para crearlo:

Define los objetivos del negocio.
Caracteriza tu público objetivo.
Identifica las necesidades del cliente.
Trabaja en las características que satisfagan dichas necesidades.

**3. Priorizar las actividades**
El backlog product puede rápidamente saturarse de ideas, de ahí la importancia de priorizarlas, según el orden en el que se desarrollarán.

👉 Apóyate en criterios de prioridad como:

importancia de la característica para el cliente/usuario (valor comercial),
cantidad de trabajo requerida,
posibles desafíos de su implementación,
habilidades adquiridas por el equipo durante su realización.
**4. Planifica el sprint backlog**

Antes de cada reunión de planificación de un sprint, revisa el backlog para confirmar que la priorización es la adecuada y tiene en cuenta factores del sprint anterior:

reacción de los clientes,
revisión de estimaciones iniciales,
aparición de nuevas limitaciones, etc.
Finalmente, determina un calendario de entrega de las características esperadas para el sprint actual. Ten cuidado de no aceptar ninguna user story adicional, en aras de que el equipo logre completar su misión.

Video ejemplo de como funciona el product backlog
https://www.youtube.com/watch?v=JuIVHk1wvcw
