### ISSUE TITLE
Metodologías de trabajo ( manifiesto agile, principios agile, procesos agile)

### ISSUE THREAD

**Issue by NicolasRuiz81** [Guillermocba/Grupo5#3]
**Recabar información sobre cada unos de estos temas, se pueden incluir imágenes y videos adicionales.**

**Comment by arnaldomacia** [comment]
Para poder explicar las "Metodologías de Trabajo" debemos primero aclarar algunas cuestiones, por ejemplo: el Ciclo de vida 
que es el conjunto de fases [o procesos] por las que pasa el sistema de software desde que se concibe [o inicio], se desarrolla 
hasta que se retira del servicio finalizando su uso. Las fases o procesos están estandarizados, es decir que existe un marco de referencia que contiene los procesos, las actividades y las tareas involucradas en el desarrollo, explotación y mantenimiento de un producto de software , abarcando la vida del sistema, desde la definición de requerimientos hasta la finalización de su uso.

Manifiesto Ágil
Por definición, las metodologías ágiles son aquellas que permiten adaptar la forma de trabajo a las condiciones del proyecto, consiguiendo flexibilidad e inmediatez en la respuesta para amoldar el proyecto y su desarrollo a las circunstancias específicas del entorno.

El Manifiesto Ágil es un documento redactado en 2001 por 17 expertos en programación que supuso un cambio radical en la forma de desarrollar ‘software’. Frente a los modelos tradicionales —excesivamente rígidos y alejados de las necesidades de los clientes—, estos gurús propusieron cuatro valores que inspiran las diferentes metodologías ágiles que han surgido desde entonces. Aunque nació en el mundo del ‘software’, la filosofía que promueve este manifiesto es extensible al desarrollo de cualquier otro producto.

Veamos en qué consisten sus valores y principios:

Valores
Los valores definidos en el Manifiesto Ágil no se centran en prácticas, metodologías o procedimientos de trabajo, sino que abogan por un cambio de mentalidad, una nueva cultura organizativa basada en cuatro pilares:

Individuos e interacciones sobre procesos y herramientas. Software funcionando sobre documentación extensiva. Colaboración con el cliente sobre negociación contractual. Respuesta ante el cambio sobre seguir un plan.

El manifiesto ágil, tal como mencionamos en un comienzo, fue firmado por expertos de desarrollo de software que llevaban varios años en la industria. Fue firmado pues por personas con amplios conocimientos y experiencia. Fue en base a esta experiencia anterior lo que les había permitido darse cuenta de que podría haber maneras diferentes de desarrollar software ya que los enfoques hasta la fecha estaban centrados en metodologías y procesos que primaban más otras cosas.

Principios
Para complementar a los valores tenemos los principios que podríamos decir que son recetas más concretas que nos permiten llevar a la práctica los valores. En el propio manifiesto ágil se incluyen 12 principios que pasamos a enumerar a continuación:

Nuestra mayor prioridad es satisfacer al cliente mediante la entrega temprana y continua de software con valor.
Aceptamos que los requisitos cambien, incluso en etapas tardías del desarrollo. Los procesos Ágiles aprovechan el cambio para proporcionar ventaja competitiva al cliente.
Entregamos software funcional frecuentemente, entre dos semanas y dos meses, con preferencia al periodo de tiempo más corto posible.
Los responsables de negocio y los desarrolladores trabajamos juntos de forma cotidiana durante todo el proyecto.
Los proyectos se desarrollan en torno a individuos motivados. Hay que darles el entorno y el apoyo que necesitan, y confiarles la ejecución del trabajo.
El método más eficiente y efectivo de comunicar información al equipo de desarrollo y entre sus miembros es la conversación cara a cara.
El software funcionando es la medida principal de progreso.
Los procesos Ágiles promueven el desarrollo sostenible. Los promotores, desarrolladores y usuarios debemos ser capaces de mantener un ritmo constante de forma indefinida.
La atención continua a la excelencia técnica y al buen diseño mejora la Agilidad.
La simplicidad, o el arte de maximizar la cantidad de trabajo no realizado, es esencial.
Las mejores arquitecturas, requisitos y diseños emergen de equipos autoorganizados.
A intervalos regulares el equipo reflexiona sobre cómo ser más efectivo para a continuación ajustar y perfeccionar su comportamiento en consecuencia.
Debemos tener siempre presente estos valores y principios en nuestro día a día ya que como comentamos anteriormente son la base sobre la que se asientan todo (reuniones, artefactos, roles). Ante la duda sobre cómo actuar o qué hacer resulta una buena solución acudir a estos principios y valores y ver que nos transmiten para decidir qué hacer.
