### ISSUE TITLE
Definición de scrum

### ISSUE THREAD

**Issue by NicolasRuiz81** [Guillermocba/Grupo5#4]
**Recabar información sobre scrum, se pueden incluir imágenes y videos adicionales que aporten al tema.**

**Comment by GalarzaBrian** [comment]
### Definición de Scrum
Scrum es marco de trabajo a través del cual las personas pueden abordar problemas complejos adaptativos, a la vez que se entregan productos de forma eficiente y creativa con el máximo valor. 
En Scrum se aplica un conjunto de buenas prácticas para trabajar de manera colaborativa y obtener así el mejor resultado posible en proyectos complejos que demandan constantes cambios y adaptaciones.

Se suele pensar que Scrum y la metodología ágil son lo mismo porque Scrum se centra en la mejora continua, que es un principio básico de la metodología ágil. Sin embargo, Scrum es un marco para realizar el trabajo, mientras que la metodología ágil es una mentalidad.
