### ISSUE TITLE
Pilares de scrum

### ISSUE THREAD

**Issue by NicolasRuiz81** [Guillermocba/Grupo5#5]
**Recabar información sobre pilares de scrum, se pueden incluir imágenes y videos adicionales que aporten al tema.**

**Comment by davidspuler** [comment]
Pilares de Scrum
Tres son los pilares que sustentan el marco de Scrum:

transparencia
inspección
adaptabilidad.
Todos y cada uno de los elementos de Scrum (roles, eventos, artefactos y reglas) contribuyen en mayor o menor medida a estos tres pilares.

La transparencia
Los aspectos significativos del proceso deben ser visibles para todos aquellos que son responsables del resultado. La
transparencia requiere que dichos aspectos sean definidos en base a un estándar común, de tal modo que los
observadores compartan un entendimiento común de lo que se están viendo.
Por ejemplo
• Deben compartir un lenguaje común todos los participantes para referirse al proceso; y,
• Aquellos que desempeñan el trabajo y quienes inspeccionan el incremento resultante deben compartir una definición
común de “Terminado” (“Done”). 

La inspección
Scrum promueve la inspección frecuente de los Artefactos y del progreso para identificar y corregir las variaciones no deseadas. La inspección tiene lugar durante: la Reunión de Planificación de Sprint, el Scrum Diario, la Revisión del Sprint y la Retrospectiva del Sprint.

La adaptación
La adaptación implica hacer los ajustes en los procesos y artefactos para minimizar la desviación. Aunque la Retrospectiva del Sprint es el momento que formalmente se reserva para llevar plantar las mejoras a implementar durante el sprint siguiente,

En el ámbito de Scrum decimos que la transparencia es un valor “neutral”, ya que por sí mismo no agrega valor. Es decir, lo que genera valor es aquello que hagas con lo que descubre gracias a la transparencia. Por ejemplo, si durante una Retrospectiva descubrimos que tendemos a centrarnos en nuestro propio trabajo individual y que no nos apoyamos unos a otros, el descubrimiento no añade valor, lo que añade valor es abordar el problema.

Para que Scrum sea efectivo cada uno de los tres pilares debe estar en su lugar, pararse y ser apoyadas – uno sin los otros disuade mucho de la eficacia de la aplicación de Scrum.

Adjunto video explicativo de cada pilar de scrum:
https://www.youtube.com/watch?v=WLfYWwTZ8_I
