### ISSUE TITLE
Definición de sprint

### ISSUE THREAD

**Issue by NicolasRuiz81** [Guillermocba/Grupo5#6]
**Recabar información sobre definición de sprint, se pueden incluir imágenes y videos adicionales que aporten al tema.**

**Comment by Guillermocba** [comment]
El sprint es un periodo de corta duración que debe finalizar con un prototipo operativo o producto parcial entregable. El mismo se repite n veces a lo largo del proyecto y permite hacer entregas de producto en partes, donde cada entrega, es un incremento de funcionalidad respecto al anterior. Esto difiere del conocido ciclo de vida en cascada muy utilizado en el campo de desarrollo de software en que, las fases del ciclo de vida (requisitos, análisis, diseño, codificación, testing, etc) se realizan una única vez y el inicio de cada fase no comienza hasta que termina la que procede.
