### ISSUE TITLE
Ceremonias de scrum, Sprint planning meeting y daily scrum meeting.

### ISSUE THREAD

**Issue by NicolasRuiz81** [Guillermocba/Grupo5#7]
**Recabar información sobre los temas asignados, se pueden incluir imágenes y videos adicionales que aporten al tema.**

**Comment by gusscamp22** [comment]
CEREMONIAS DEL SPRINT:
Sprint Planning Meeting:(reunion de planificacion del sprint) Se produce al realizar cada sprint y tiene por objetivo decidir que se va arealizar en cada sprint.
![sprint](https://user-images.githubusercontent.com/106712601/177049829-7115efa0-ed76-4a93-a3bb-4eb6d97527bd.jpeg)
Daily Scrum Meeting: (reunion periodica) Se produce diariamente, y tiene un maximo de duracion de 20 minutos. Tiene por objeto tratar lo que se hizo, que se va hacer y que problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.
![scrum12](https://user-images.githubusercontent.com/106712601/177050900-397bbf18-1b36-4957-a30f-cc3bc960911c.jpg)
