### ISSUE TITLE
Ceremonias de scrum: Sprint review meeting y sprint retrospective meeting

### ISSUE THREAD

**Issue by NicolasRuiz81** [Guillermocba/Grupo5#8]
**Recabar información sobre los temas asignados, se pueden incluir imágenes y videos adicionales que aporten al tema.**

**Comment by matiassorrentino** [comment]
**Sprint Review Meeting** (reunión de revisión del Sprint). Se produce al finalizar el Sprint y tiene por objeto mostrar qué es lo que se ha completado y qué no. 

**Sprint Retrospective Meeting** (reunión de retrospectiva del Sprint). Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.
