### ISSUE TITLE
Scrum team (Roles)

### ISSUE THREAD

**Issue by NicolasRuiz81** [Guillermocba/Grupo5#9]
**Recabar información sobre los scrum team, se pueden incluir imágenes y videos adicionales que aporten al tema.**

**Comment by Melga10** [comment]
Un Scrum Team está compuesto por un Product Owner, el equipo de desarrollo y un Scrum Master. Es decir, se llama Scrum Team a aquellos equipos donde se pueden encontrar los tres roles.
Los roles no son personas físicas, son roles (“etiquetas”), por lo que lo importante es que un Scrum Team siempre tenga a los tres roles representados, y que, en todo momento, todo el Scrum Team sepa quien está desempeñando qué rol.
Por ejemplo, tres Scrum Teams pueden compartir el mismo Product Owner. Lo importante es que cada Scrum Team por separado sabe quién es su Product Owner.
Los Scrum Teams están diseñados para ser multifuncionales y auto-organizados. Ellos deciden cómo realizar su trabajo, y tienen todas las competencias necesarias para ello dentro del equipo (es decir, no tienen dependencias con terceros que se encuentren fuera del equipo).
El objetivo de un Scrum Team es entregar productos de forma iterativa e incremental, maximizando las oportunidades de feedback.

Product Owner
El Product Owner es el encargado de optimizar y maximizar el valor del producto, siendo la persona encargada de gestionar el flujo de valor del producto a través del Product Backlog. Adicionalmente, es fundamental su labor como interlocutor con los stakeholders y sponsors del proyecto, así como su faceta de altavoz de las peticiones y requerimientos de los clientes. Si el Product Owner también juega el rol de representante de negocio, su trabajo también aportará valor al producto.

Scrum Master
El Scrum Master tiene dos funciones principales dentro del marco de trabajo: gestionar el proceso Scrum y ayudar a eliminar impedimentos que puedan afectar a la entrega del producto. Además, se encarga de las labores de mentoring y formación, coaching y de facilitar reuniones y eventos si es necesario.


El equipo de desarrollo
El equipo de desarrollo suele estar formado por entre 3 a 9 profesionales que se encargan de desarrollar el producto, auto-organizándose y auto-gestionándose para conseguir entregar un incremento de software al final del ciclo de desarrollo.
El equipo de desarrollo se encargará de crear un incremento terminado a partir de los elementos del Product Backlog seleccionados (Sprint Backlog) durante el Sprint Planning.
Es importante que en la metodología Scrum todos los miembros del equipo de desarrollo conozcan su rol, siendo solo uno común para todos, independientemente del número de miembros que tenga el equipo y cuales sean sus roles internos. Cómo el equipo de desarrollo decida gestionarse internamente es su propia responsabilidad y tendrá que rendir cuentas por ello como uno solo; hay que evitar intervenir en sus dinámicas.
Habitualmente son equipos ‘cross-funcional’, capaces de generar un incremento terminado de principio a fin, sin otras dependencias externas.
